config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    root 'recruitments#index'
    devise_for :users, controllers: {
          registrations: 'users/registrations'
    }
    resources :recruitments do
      collection do
        match 'search', to: 'recruitments#search', via: [:get, :post]
      end
    end
    resources :users, only: [:update, :show]
    resources :friend_relations, only: [:index, :create, :update, :destroy]
    patch 'friend_relation/:id', to: 'friend_relations#index'
    resources :chat_rooms, only: [:index]
    resources :messages, only: [:get, :create, :show]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
  has_many :participants
  has_many :messages

  def last_time(room, current_user)
    last_message = room.messages.where.not(user_id: current_user.id).last
    if last_message.present?
      time = last_message.created_at
    else
      time = room.created_at
    end
  end

  def get_speaker(room, current_user)
    speaker_id = room.participants.where.not(user_id: current_user.id).pluck(:user_id)[0]
    @speaker = UserDetail.find_by(user_id: speaker_id)
  end

  def self.get_newly_message(current_user, other_user)
    current_user_rooms = Participant.where(user_id: current_user.id).pluck(:chat_room_id)
    other_user_rooms = Participant.where(user_id: other_user.id).pluck(:chat_room_id)
    match_room = (current_user_rooms & other_user_rooms).first
    messages = Message.where(chat_room_id: match_room).order(created_at: "DESC")
    return false unless messages.present?
    new_message = messages.find_by(user_id: other_user.id, read: "未読")
    if new_message.present?
      return new_message.message
    else
      return false
    end
  end
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
  def index
    @chat_rooms = current_user.chat_rooms.sort_by { |chat_room| chat_room.last_time(chat_room, current_user) }.reverse
    @chat_rooms = Kaminari.paginate_array(@chat_rooms).page(params[:page]).per(10)
    @chat_users = @chat_rooms.map {|room|
      room.get_speaker(room, current_user)
    }
  end
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/views/chat_rooms/index.html.erb
<div>
  <h1 class="page-title"><%= t("chat_rooms.index.chat_room_list") %></h1>
</div>
<% @chat_users.each do |chat_user| %>
  <% if FriendRelation.check_friend_status_for_chat(current_user, chat_user) == true %>
    <div class="container main-contents">
      <div class="row">
        <div class="col-lg-3">
        </div>
        <div class="col-lg-6">
          <div class="chatroom-box">
            <%= link_to message_path(chat_user.user.id), id: 'message-box' do %>
              <div class="chat_img-position">
                <%= image_tag chat_user.profile_picture.url, size: '70x70' %>
              </div>
              <div class="main-chatroom-content">
                <% message = ChatRoom.get_newly_message(current_user, chat_user) %>
                <% if message.present? %>
                  <div class="chatroom-name-box">
                    <p class='chatroom-name'><%= chat_user.account_name %></p>
                  </div>
                  <div class="new-message">
                    <p class="chat-message"><%= message %></p>
                  </div>
                <% else %>
                  <div class="chatroom-name-box-false">
                    <p class='chatroom-name'><%= chat_user.account_name %></p>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-lg-3">
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= paginate @chat_rooms %>