config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    root 'recruitments#index'
    devise_for :users, controllers: {
          registrations: 'users/registrations'
    }
    resources :recruitments do
      collection do
        match 'search', to: 'recruitments#search', via: [:get, :post]
      end
    end
    resources :users, only: [:update, :show]
    resources :friend_relations, only: [:index, :create, :update, :destroy]
    patch 'friend_relation/:id', to: 'friend_relations#index'
    resources :chat_rooms, only: [:index]
    resources :messages, only: [:get, :create, :show]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/recruitment.rb
class Recruitment < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 128}
  validates :content, presence: true, length: { maximum: 3000}

  def relative_post_date(updated_at, locale)
    sec = (Time.zone.now - updated_at).round
    if locale == "ja"
      days = sec / (60 * 60 * 24)
        return "#{days}日前" unless days.zero?
      hours = sec / (60 * 60)
        return "#{hours}時間前" unless hours.zero?
      min = sec / 60
        return "#{min}分前" unless min.zero?
      "#{sec}秒前"
    else
      days = sec / (60 * 60 * 24)
        return "#{days}days ago" unless days.zero?
      hours = sec / (60 * 60)
        return "#{hours}hours ago " unless hours.zero?
      min = sec / 60
        return "#{min}minutes ago" unless min.zero?
      "#{sec}seconds ago"
    end
  end

end

app/controllers/recruitments_controller.rb
class RecruitmentsController < ApplicationController

  before_action :set_recruitment, only: %i[show edit update destroy]
  before_action :set_filter, only: %i[index search]


  def index
    @recruitments = Recruitment.where.not(user_id: current_user.id).order(updated_at: :desc).page(params[:page])
  end

  def new
    if params[:back]
      @recruitment = Recruitment.new(recruitment_params)
    else
      @recruitment = Recruitment.new
    end
  end

  def create
    @recruitment = current_user.recruitments.build(recruitment_params)
    if params[:back]
      render :new
    else
      if @recruitment.save
        redirect_to recruitments_path, notice: "募集文を投稿しました。"
      else
        render :new
      end
    end
  end

  def show
    @user = User.find(Recruitment.find(params[:id]).user_id)
    redirect_to recruitments_path, notice: "不正なアクセスです。" if FriendRelation.check_block_status(current_user, @user)
    @profile = @user.user_detail
    @learn_languages = @user.learn_languages
    @speak_languages = @user.speak_languages
    @games = @user.games
    @game_platforms = @games.map { |game|
      game.game_relation_game_platforms
    }.flatten!
    @game_account = @user.game_account
  end

  def edit
    user_id = Recruitment.find(params[:id]).user_id
    redirect_to recruitments_path , notice: "不正なアクセスです。" unless current_user.id == user_id
  end

  def update
    if @recruitment.update(recruitment_params)
      redirect_to recruitment_path(params[:id]), notice: '投稿を編集しました。'
    else
      render :edit
    end
  end

  def destroy
    @recruitment.destroy
    redirect_to recruitments_path, notice: '投稿を削除しました。'
  end

  def confirm
    @recruitment = Recruitment.new(recruitment_params)
    render :new if @recruitment.invalid
  end

  def search
    @recruitments = @search.result.where.not(user_id: current_user.id).order(updated_at: :desc)
    if @selected_learn_language.present?
      @recruitments = @recruitments.select { |n|
        n.user.learn_languages.each do |learn_language|
          if learn_language.learn_language == @selected_learn_language
            break learn_language.learn_language_status == "公開" ||
            (learn_language.learn_language_status == "フレンドのみ公開" &&
              FriendRelation.check_friend_status(current_user, User.find(n.user_id))
            )
          end
        end
      }
    end
    if @selected_speak_language.present?
      @recruitments = @recruitments.select { |n|
        n.user.speak_languages.each do |speak_language|
          if speak_language.speak_language == @selected_speak_language
            break speak_language.speak_language_status == "公開" ||
            (speak_language.speak_language_status == "フレンドのみ公開" &&
              FriendRelation.check_friend_status(current_user, User.find(n.user_id))
            )
          end
        end
      }
    end
    @recruitments = Kaminari.paginate_array(@recruitments).page(params[:page]).per(10)
  end


  private
  def recruitment_params
    params.require(:recruitment).permit(:title, :content)
  end

  def set_recruitment
    begin
      @recruitment = Recruitment.find(params[:id])
    rescue
      recruitments_search_path
    end
  end

  def set_filter
    @search = Recruitment.ransack(params[:q])
    if params[:q].present?
      @selected_learn_language = params[:q][:user_learn_languages_learn_language_eq]
      @selected_speak_language = params[:q][:user_speak_languages_speak_language_eq]
    end
    @game_platform_list = GamePlatform.select("name")
    @learn_language_list = LearnLanguage.select('learn_language').distinct
    @speak_language_list = SpeakLanguage.select('speak_language').distinct
  end

end

app/helpers/recruitments_helper.rb
module RecruitmentsHelper
end

app/views/recruitments/_form.html.erb
<% if @recruitment.errors.any? %>
  <div class="container main-contents">
    <div class="row">
      <div class="col-lg-1">
      </div>
      <div class="col-lg-10">
        <div id="error_explanation">
          <ul>
            <% @recruitment.errors.full_messages.each do |msg| %>
              <li class="alert alert-danger"><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
      <div class="col-lg-1">
      </div>
    </div>
  </div>
<% end %>
<div class="container main-contents">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-10 contents">
      <%= form_with(model: @recruitment, local: true) do |form| %>
        <div class="form_box">
          <%= form.label :title, t("recruitments.form.title"), class: "content_field form-label" %>
          <% if params[:locale] == "ja" %>
            <%= form.text_field :title, id: 'recruitment_title', placeholder: "タイトルを入力してください。", class: "form-control" %>
          <% else %>
            <%= form.text_field :title, id: 'recruitment_title', placeholder: "Please enter a title.", class: "form-control" %>
          <% end %>
        </div>
        <div class="form_box">
          <%= form.label :content, t("recruitments.form.recruitment_content"), class: "content_field form-label" %></p>
          <% if params[:locale] == "ja" %>
            <%= form.text_area :content, size: "30x20", id: 'recruitment_content', placeholder: "募集する内容を入力してください。", class: "form-control overflow-auto" %>
          <% else %>
            <%= form.text_area :content, size: "30x20", id: 'recruitment_content', placeholder: "Please enter the content you want to recruit.", class: "form-control overflow-auto" %>
          <% end %>
        </div>
        <div class="form_box basic-button">
          <% if params[:locale] == "ja" %>
            <%= form.submit '登録する', id: '登録する', class: "btn btn-success btn-lg w-20" %>
          <% else %>
            <%= form.submit 'Register', id: '登録する', class: "btn btn-success btn-lg w-20" %>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="col-lg-1 ">
    </div>
  </div>
</div>

app/views/recruitments/_recruitment_index.html.erb
<div>
  <h1 class="page-title"><%= t("recruitments.recruitment_index.recruitment_list") %></h1>
</div>
<div class="container main-contents">
  <div class="row">
    <div class="col-lg-3">
      <% if notice.present? || alert.present? || (current_user.count_application(current_user) > 0) || current_user.check_newly_arrived_messages(current_user) %>
        <div class="information info-field">
          <div class="contents">
            <% if notice.present? %><p class="notice text-warning"><%= notice %></p><% end %>
            <% if alert.present? %><p class="alert text-danger"><%= alert %></p><% end %>
            <% if current_user.count_application(current_user) > 0 %>
              <%= link_to "#{t("recruitments.recruitment_index.front_receive_friend_request")} #{current_user.count_application(current_user)} #{t("recruitments.recruitment_index.behind_receive_friend_request")}", friend_relations_path, class: "text-warning", id: "receive-friend-request" %><br/>
            <% end %>
            <% if current_user.check_newly_arrived_messages(current_user) %>
              <%= link_to "#{t("recruitments.recruitment_index.receive_message")}", chat_rooms_path, class: "text-warning" %>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="search-data">
        <div class="contents">
          <h3 class="form-label"><%= t("recruitments.recruitment_index.search") %></h3>
          <%= search_form_for @search, url: search_recruitments_path, method: :search do |f| %>
            <% if params[:locale] == "ja" %>
              <%= f.search_field :title_or_content_or_user_games_name_or_user_user_detail_self_introduction_cont, placeholder: "キーワード検索", class: 'form-control form-awesome' %><br />
            <% else %>
              <%= f.search_field :title_or_content_or_user_games_name_or_user_user_detail_self_introduction_cont, placeholder: "Keyword search", class: 'form-control form-awesome' %><br />
            <% end %>
            <div class="search-box">
              <%= f.label :user_games_game_relations_game_platform_name_eq, t("recruitments.recruitment_index.game_platform"), class: "form-label" %><br />
              <%= f.collection_select :user_games_game_relations_game_platform_name_eq, @game_platform_list, :name, :name,  include_blank: '-------------------', class: 'form-control form-awesome select-size-auto' %>
            </div>
            <div class="search-box">
              <%= f.label :user_learn_languages_learn_language_eq, t("recruitments.recruitment_index.learning_language"), class: "text-padding-left form-label" %><br />
              <%= f.collection_select :user_learn_languages_learn_language_eq, @learn_language_list, :learn_language, :learn_language,  include_blank: '-----------------', class: 'form-control form-awesome' %>
            </div>
            <div class="search-box">
              <%= f.label :user_speak_languages_speak_language_eq, t("recruitments.recruitment_index.speaking_language"), class: "text-padding-left form-label" %><br />
              <%= f.collection_select :user_speak_languages_speak_language_eq, @speak_language_list, :speak_language, :speak_language,  include_blank: '-----------------', class: 'form-control form-awesome' %>
            </div>
            <div class="basic-button">
              <% if params[:locale] == "ja" %>
                <%= f.submit '検索', class: "btn btn-success btn-lg search-btn" %>
              <% else %>
                <%= f.submit 'Search', class: "btn btn-success btn-lg search-btn" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      <br />
    </div>
    <div class="col-lg-1">
    </div>
    <div class="col-lg-5">
      <% @recruitments.each do |recruitment| %>
        <% unless FriendRelation.check_block_status(current_user.id, recruitment.user_id) %>
          <article class="recruitment-post">
            <%= link_to recruitment_path(recruitment.id), class: 'list-recruitments', id: 'recruit' do %>
              <div class="img-position">
                <%= image_tag recruitment.user.user_detail.profile_picture.url, class: 'recruitment-img' %>
              </div>
              <div class="main-article">
                <div class='article-user'>
                  <p class='article-user-name'><%= recruitment.user.user_detail.account_name %></p>
                </div>
                <div class='article-time'>
                  <p class="article-date"><%= recruitment.relative_post_date(recruitment.updated_at, params[:locale]) %></p>
                </div>
                <div>
                  <p class='article-title'><%= recruitment.title %></p>
                </div>
              </div>
            <% end %>
            <br />
          </article>
        <% end %>
      <% end %>
      <%= paginate @recruitments %>
    </div>
    <div class="col-lg-3">
      <div class="information new-post d-grid gap-2 d-lg-block">
        <% if params[:locale] == "ja" %>
          <%= button_to "新しく募集を作成する", new_recruitment_path, method: :get, class: "p-3 btn btn-success btn-lg w-75" %>
        <% else %>
          <%= button_to "Post a new recruitment", new_recruitment_path, method: :get, class: "p-3 btn btn-success btn-lg w-75" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/recruitments/edit.html.erb
<div>
  <h1 class="page-title"><%= t("recruitments.edit.edit_post_page") %></h1>
</div>
<%= render 'form' %>

app/views/recruitments/index.html.erb
<%= render 'recruitment_index' %>

app/views/recruitments/new.html.erb
<div>
  <h1 class="page-title"><%= t("recruitments.new.post_page") %></h1>
</div>
<%= render 'form' %>

app/views/recruitments/search.html.erb
<%= render 'recruitment_index' %>

app/views/recruitments/show.html.erb
<div>
  <h1 class="page-title">
    <% if current_user.id == @user.id %>
      <%= t("recruitments.show.my_recruitment_page") %>
    <% else %>
      <%= @profile.account_name %><%= t("recruitments.show.recruitment_detail") %>
    <% end %>
  </h1>
</div>
<div class="container main-contents">
  <div class="row">
    <div class="col-lg-1">
    </div>
    <div class="col-lg-10 contents">
      <div>
        <h2 class="content_field form-label recruitment-title"><%= t("recruitments.show.title") %></h2>
        <p class="form-control show-content"><%= @recruitment.title %></p>
      </div>
      <div>
        <h2 class="content_field form-label recruitment-title"><%= t("recruitments.show.recruitment_content") %></h2>
        <div class="show-content">
          <%= safe_join(@recruitment.content.split("\n"), tag(:br, class: "form-control textarea-show-box") ) %>
        </div>
      </div>
      <% if current_user.id == @user.id %>
        <% if params[:locale] == "ja" %>
          <div class="basic-button">
            <%= button_to "投稿編集", edit_recruitment_path, method: :get, class: "btn btn-success btn-lg w-25" %>
          </div>
          <div class="danger-button">
            <%= button_to "投稿削除", recruitment_path, { method: :delete, class: "btn btn-danger btn-lg w-25", data: { confirm: '本当に削除しますか？' } } %>
          </div>
        <% else %>
          <div class="basic-button">
            <%= button_to "Edit a post", edit_recruitment_path, method: :get, class: "btn btn-success btn-lg w-25" %>
          </div>
          <div class="danger-button">
            <%= button_to "Delete a post", recruitment_path, { method: :delete, class: "btn btn-danger btn-lg w-25", data: { confirm: 'Are you sure you want to delete it?' } } %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<br /><br />
<%= render './users/user_show' %>