config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    root 'recruitments#index'
    devise_for :users, controllers: {
          registrations: 'users/registrations'
    }
    resources :recruitments do
      collection do
        match 'search', to: 'recruitments#search', via: [:get, :post]
      end
    end
    resources :users, only: [:update, :show]
    resources :friend_relations, only: [:index, :create, :update, :destroy]
    patch 'friend_relation/:id', to: 'friend_relations#index'
    resources :chat_rooms, only: [:index]
    resources :messages, only: [:get, :create, :show]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :lockable, :timeoutable, :trackable
          #:confirmable, :omniauthable

  has_one :user_detail, dependent: :destroy
  accepts_nested_attributes_for :user_detail, allow_destroy: true
  has_one :game_account, dependent: :destroy
  accepts_nested_attributes_for :game_account, allow_destroy: true

  has_many :games, dependent: :destroy
  accepts_nested_attributes_for :games, allow_destroy: true
  has_many :learn_languages, dependent: :destroy
  accepts_nested_attributes_for :learn_languages, allow_destroy: true
  has_many :speak_languages, dependent: :destroy
  accepts_nested_attributes_for :speak_languages, allow_destroy: true

  has_many :recruitments, dependent: :destroy
  has_many :participants, dependent: :destroy
  has_many :chat_rooms, through: :participants
  has_many :messages, dependent: :destroy

  has_many :friend_relations, foreign_key: 'from_applicant_id', dependent: :destroy
  has_many :reverse_of_relations, foreign_key: 'to_target_id', class_name: 'FriendRelation', dependent: :destroy
  has_many :applicant, through: :friend_relations, source: :to_target
  has_many :reverse_of_target, through: :reverse_of_relations, source: :from_applicant

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }}


  def send_friend_request!(other_user)
    friend_relations.create!(to_target_id: other_user.id, status: "申請中")
  end

  def check_already_friend?(other_user)
    friend_relations.find_by(to_target_id: other_user.id)
  end

  def update_friend_status!(other_user)
    friend_relations.find_by(to_target_id: other_user.id).update!(status: "ブロック")
  end

  def delete_friend!(other_user)
    friend_relations.find_by(to_target_id: other_user.id).destroy
  end

  def release_info(current_user, user, column, status)
    if current_user.id == user.id || (column.present? && (status == "公開" || (FriendRelation.get_friend_status(current_user, user) == "フレンド" && status == "フレンドのみ公開")))
      return true
    end
  end

  def count_application(current_user)
    current_user.reverse_of_relations.select{ | application |
      application.status == "申請中"
    }.size
  end

  def check_newly_arrived_messages(current_user)
    if current_user.chat_rooms.present?
      current_user.chat_rooms.each do |chat_room|
        messages = chat_room.messages.order(created_at: "DESC")
        new_message = messages.where(read: "未読").where.not(user_id: current_user.id)
        if new_message.present?
          return true
        else
          return false
        end
      end
    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_action :authenticate_user!, only: [:new, :create]
  before_action :reset_gender, only: [:create, :update]

  # GET /resource/sign_up
  def new
    super
    @user = User.new
  end

  # POST /resource
  def create
    super
    if params[:back]
      render :new
    end
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    super
  end

  private
    def reset_gender
      unless params[:locale] == "ja"
        if params[:user][:user_detail_attributes][:gender] == "Male"
          params[:user][:user_detail_attributes][:gender] = 0
        elsif params[:user][:user_detail_attributes][:gender] == "Female"
          params[:user][:user_detail_attributes][:gender] = 1
        else
          params[:user][:user_detail_attributes][:gender] = 2
        end
      end
    end


  protected
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    user_path(@user.id)
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  skip_before_action :authenticate_user!, only: [:new, :create]
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def update

  end

  def show
    @user = User.find(params[:id])
    redirect_to recruitments_path, notice: "不正なアクセスです。" if FriendRelation.check_block_status(current_user, @user)
    @profile = @user.user_detail
    @learn_languages = @user.learn_languages
    @speak_languages = @user.speak_languages
    @games = @user.games
    @game_platforms = @games.map { |game|
      game.game_relation_game_platforms
    }.flatten!
    @game_account = @user.game_account
    @recruitments = Recruitment.where(user_id: params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_friend_request.erb
<div id="friend_request_<%= user.id %>">
  <%= form_with(model: current_user.friend_relations.build(to_target_id: user.id))  do |f| %>
    <%= f.hidden_field :from_applicant_id %>
    <%= f.submit "フレンド申請" %>
  <% end %>
</div>

app/views/users/_friend_request.html.erb
<div id="friend_request_<%= user.id %>">
  <% if current_user.id == user.id %>
    <p>自分のアカウントです</p>
  <!-- フレンドではない場合 -->
  <% elsif FriendRelation.check_already_friend?(current_user, user) == false %>
    <%= form_with(model: current_user.friend_relations.build(to_target_id: user.id))  do |f| %>
      <%= f.hidden_field :to_target_id %>
      <%= f.submit "フレンド申請" %>
    <% end %>
  <!-- 申請中かつ自分が申請者の場合 -->
  <% elsif FriendRelation.are_you_applicant?(current_user, user) %>
    <%= form_with(model: current_user.friend_relations.find_by(to_target_id: user.id), method: :delete ) do |f| %>
      <%= f.hidden_field :to_target_id %>
      <%= f.submit "申請をキャンセル", data: { confirm: "申請をキャンセルしますか？"}  %>
    <% end %>
  <!-- 申請中かつ自分が申請を受け取ったの場合 -->
  <% elsif FriendRelation.are_you_receiver?(current_user, user)%>
    <%= form_with(model: user.friend_relations.find_by(to_target_id: current_user.id), method: :patch ) do |f| %>
      <%= f.hidden_field :status, value: "フレンド" %>
      <%= f.submit "申請を許可" %>
    <% end %>
    <%= form_with(model: user.friend_relations.find_by(to_target_id: current_user.id), method: :patch ) do |f| %>
      <%= f.hidden_field :status, value: "ブロック" %>
      <%= f.submit "申請を却下", data: { confirm: "申請を却下します。よろしいですか？"}  %>
    <% end %>
  <!-- フレンドの場合 -->
  <% elsif FriendRelation.get_friend_status(current_user, user) == "フレンド" %>
    <%= form_with(model: user.friend_relations.find_by(to_target_id: current_user.id), method: :patch ) do |f| %>
      <%= f.hidden_field :status, value: "ブロック" %>
      <%= f.submit "フレンドを解除", data: { confirm: "フレンドを解除しますか？"} %>
    <% end %>
  <% else %>
    <!-- ステータスがブロックの場合 -->
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <h1 class="page-title">
    <% if current_user.id == @user.id %>
      <%= t("users.show.my_page") %>
    <% else %>
      <%= @profile.account_name %><%= t("users.show.details") %>
    <% end %>
  </h1>
</div>
<%= render 'user_show' %>
<% if @recruitments.present? %>
  <div>
    <h1 class="page-title"><%= t("users.show.recruiting_posts") %></h1>
  </div>
<% end %>
<div class="container main-contents">
  <div class="row">
    <div class="col-md-2">
    </div>
    <div class="col-md-8 profile-field">
      <% @recruitments.each do |recruitment| %>
        <br />
        <div class="form_box">
          <div class="profile-post">
            <%= link_to recruitment.title, recruitment_path(recruitment.id), class: "recruitment-title", id: "history-recruitment" %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-md-2 button-padding">
    </div>
  </div>
</div>