config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  scope "(:locale)", locale: /#{I18n.available_locales.map(&:to_s).join("|")}/ do
    root 'recruitments#index'
    devise_for :users, controllers: {
          registrations: 'users/registrations'
    }
    resources :recruitments do
      collection do
        match 'search', to: 'recruitments#search', via: [:get, :post]
      end
    end
    resources :users, only: [:update, :show]
    resources :friend_relations, only: [:index, :create, :update, :destroy]
    patch 'friend_relation/:id', to: 'friend_relations#index'
    resources :chat_rooms, only: [:index]
    resources :messages, only: [:get, :create, :show]
  end

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/views/layouts/_google_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=G-2348F68JJS"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-2348F68JJS');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Langamer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.4.1/jquery.jscroll.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&family=Hina+Mincho&family=Shippori+Mincho&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <% if Rails.env.production? %>
      <%= render 'layouts/google_analytics' %>
    <% end %>
  </head>

  <body>
    <% if user_signed_in? %>
      <nav class="navbar navbar-expand-md navbar-dark bg-black fixed-top border-bottom langamer-logo header ">
      <div class="container-fluid">
        <%= link_to "Langamer", root_path, class: "navbar-brand langamer-logo" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
          <ul class="navbar-nav header-left">
            <% if current_user.try(:admin?) %>
              <li class="nav-item">
                <%= link_to '管理者', rails_admin_path, class: "nav-link link-btn d-flex" %>
              </li>
            <% end %>
            <li class="nav-item">
              <% if params[:locale] == "en" || params[:locale].blank? %>
                <%= link_to "日本語に切替", "/ja", class: "nav-link link-btn d-flex" %>
              <% elsif params[:locale] == "ja" %>
                <%= link_to "Switch to English", "/en", class: "nav-link link-btn d-flex" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "#{t("layouts.application.my_page")}", user_path(current_user.id), class: "nav-link link-btn d-flex", id: "my-page" %>
            </li>
            <li class="nav-item">
              <%= link_to "#{t("layouts.application.message")}", chat_rooms_path, class: "nav-link link-btn d-flex", id: "message-list" %>
            </li>
            <li class="nav-item">
              <%= link_to "#{t("layouts.application.sign_out")}", destroy_user_session_path, method: :delete, class: "nav-link link-btn d-flex" %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>

    <%= yield %>

    <% if user_signed_in? %>
      <div class="border-top footer-border"></div>
    <% end %>
    <footer class="p-5 bg-transparent text-dark">
      <p id="copyright">Copyright © 2022 Langamer All RIGHTS RESERVED.</p>
    </footer>
  </body>
</html>